### ISSUE TITLE
Embed an image of the map

### ISSUE THREAD

**Issue by thefinn93** [SamWhited/OpenShareLocationPlugin#10]
When I use Google Hangouts to share a location, it embeds a static map in the chat window, clicking it opens the interactive map. Open Share Location Plugin ought to do this as well

**Comment by SamWhited** [comment]
Conversations would need to support this first. You might try filing an issue upstream.

**Comment by SamWhited** [comment]
Note that I'm moving this repo to Bitbucket. Since this issue is an upstream issue which isn't likely to be fixed any time soon, I didn't bother reopening it there (but you're welcome to if you want a place to track it in case anything changes and we decide to work on it).
