### ISSUE TITLE
App disabled on F-Droid?

### ISSUE THREAD

**Issue by github-k8n** [SamWhited/OpenShareLocationPlugin#11]
Is there a reason why the app is disabled in the f-droid repository?
I don't see any further information on the page, just
"This app is disabled and does not appear in the repo"
https://f-droid.org/wiki/page/com.samwhited.opensharelocationplugin

**Comment by SamWhited** [comment]
The F-Droid guys and I got into a bit of an argument and I asked them to take it down. They do not currently put the authors name on the download page (from which you can download the binary) or bundle it with the binary in any way. As far as someone visiting the main page for the app can tell, it was written by F-Droid. I asked them to respect my authorship info and they told me no, so I asked them to remove my app as their site was in violation of the BSD license.

If they start including authors names on the download page for their apps, I'll happily let them put it back up. More information in [this issue](https://gitlab.com/fdroid/fdroidserver/issues/90).

**Comment by schiesbn** [comment]
Is there a way to install it without the Google play store? Maybe you can provide a apk or a fdroid repository? Kind of ironic that I looked for your plugin because I don't use the gapps and now the only way to install it seems to be the play store.

**Comment by SamWhited** [comment]
There are apks available on the releases section of Github, or you can build it.

**Comment by schiesbn** [comment]
Great, didn't saw it... Thanks!
