### ISSUE TITLE
Inclusion into F-Droid repository

### ISSUE THREAD

**Issue by jplitza** [SamWhited/OpenShareLocationPlugin#12]
Thanks so much for this non-Google version of the plugin!

I wanted to install it via the open source app repository [F-Droid](https://f-droid.org/), but didn't find it there. After some digging and asking, apparently it was once present there but then taken down as consequence of a [DCMA threat](https://gitlab.com/fdroid/fdroiddata/issues/178#note_1243157). This confuses me (and the Android people) a bit. Could you clear this up, @SamWhited? As it comes totally without Google dependencies and is open source according to its license, it should be able to include it there, no?

**Comment by SamWhited** [comment]
See #11
