### ISSUE TITLE
[Feature Request] make marker more visible 

### ISSUE THREAD

**Issue by iNPUTmice** [SamWhited/OpenShareLocationPlugin#5]
The gray marker for is a bit difficult to see some times. (Especially in cities with a lot of roads that are mainly gray themselves)
A suggestion would be to change the marker to use the 'Conversations green'. Which in turn might cause trouble when the marker is in a more urban/park-y environment where the map colors are mostly greenish.
With a little more work you might be able to make the marker green with a white? outline

**Comment by SamWhited** [comment]
I thought about using this:

![marker](https://cloud.githubusercontent.com/assets/512573/6859651/4f032a08-d3e9-11e4-964f-ff843e2efb90.png)

but it didn't come across at small sizes very well either.

Will probably just color it red with a slight outline like every other icon out there.

**Comment by SamWhited** [comment]
Actually, with a slightly thicker outline that works a bit better... and, (purely by mistake) it almost looks like a "C" for Conversations in the middle cutout:

![marker](https://cloud.githubusercontent.com/assets/512573/6859861/4faedc56-d3ec-11e4-8f93-eb954c5d82f9.png)
