### ISSUE TITLE
Allow received geo: intents to be sent to a contact

### ISSUE THREAD

**Issue by dicer** [SamWhited/OpenShareLocationPlugin#7]
I have seen that the plugin can get geo: intents. So the user looks for the place she wants to share on osmand, selects share location and the geo: type. The intent selector comes up and she selects the share location plugin. 
What currently happens is that the plugin only shows the location. No way to send it to a contact. Wouldn't it be great if it could?

**Comment by SamWhited** [comment]
This should already be done; is the share button at the top not showing up for you?

**Comment by dicer** [comment]
Oh yeah! I didn't realize I have to share it back to conversations a second time :) My bad. A bit of a rough user experience but since the normal conversations doesn't support locations, this is understandable.
