### ISSUE TITLE
Make marker placeable

### ISSUE THREAD

**Issue by dicer** [SamWhited/OpenShareLocationPlugin#8]
I know that this is mainly for sharing the current position of the user. Two reasons why I would like to see dragable marker:

1. User might be inside and NetworkLocation is not working well

2. User wants to send the location of a meeting place

Both usecases would be extremely helpful! Especially the second one brings up a few questions though: Is starting from the current location enough? What if we meet several cities away? (not sure if this would be totally out of scope already).

I guess searching the location the user is interested in is not a job for this plugin altogether. I just opened issue #7 which I think is a better way to handle this. So the dragable marker should just start at the current location, right?

**Comment by SamWhited** [comment]
I'm not sure how I feel about this; I like the idea, but I also like keeping the plugin simple (and making it just about sending the current location). I'll think about it a bit. I'd also file this issue against the official plugin as well; I'll definitely try to keep feature parity with that, but I'm not sure if I want to implement too many things that it doesn't do.

**Comment by dicer** [comment]
Well, the plugin is not called ShareUserLocationPlugin ;) I can understand your doubts though. Not asking for some new GUI though. It could be the GUI that is already there, just making the marker moveable.

I'll also file it against the original and link this thread

**Comment by SamWhited** [comment]
I decided to experiment with this on [this branch](https://github.com/SamWhited/OpenShareLocationPlugin/commit/201d205ff58e5bf90eec6e94f06001724208a9d3) to see what the UI would look like (currently it will only work on API 21+). I still can't decide if I like it or not; it adds a lot of complication, and makes the UI more cumbersome. The functionality is useful though.

![screenshot_2015-04-28-23-44-55](https://cloud.githubusercontent.com/assets/512573/7384903/43085228-ee01-11e4-9efe-28a95181c783.png)

**Comment by SamWhited** [comment]
I was thinking about this some more and I'm not sure if I've done the UX correctly. Currently the floating action button means "pin the sent location to the users current location". Instead it might be better to just always make the pin placeable and make the button just be a "go to current location" button.

Not sure what other apps do (and still not sure I like the button there). If anyone has suggestions, I'd love to hear them.

**Comment by dicer** [comment]
I think I agree: The button doesn't need to be there at all. It might help the user, but in this situation it might also confuse. I guess removing or leaving it there is not that big a deal UX-wise as it is not cluttered at all.
The functionality should be "go-back-to-my-current-position" though and not the replacement of the marker. This is its meaning in every other app I've seen  and would otherwise confuse people.

I imagine the use of the button as a "take-me-back-cause-I-am-lost-on-the-map" usecase. You know, the user scrolled somewhere, has no idea where and wants to go back where she/he started. In that case it might actually be good to also reset the location marker to the current position. It should have another design then though! The current buttons usual meaning is not reset usually. On the other hand it might be intuitive to the user to just cancel and try again, so no extra button needed.

Hope you get what I mean.

**Comment by SamWhited** [comment]
> The button doesn't need to be there at all.

I don't agree with this part (the button needs to be there)

>  The functionality should be "go-back-to-my-current-position" though and not the replacement of the marker.

I do agree with this; after using it for a bit, it makes more sense for it to just jump back to the users position if GPS is enabled. The marker will be replaced either way (since it will just be locked to the middle of the screen).

I'd still have to figure out where the button should go (or how it should look if it still remains a floating action button) on Android <5 devices.

**Comment by SamWhited** [comment]
Changed the behavior to work as described above in the branch. I still have some reservations about merging this though:

1. No idea what the Android 4.x UI should look like (might just make a 4.x compatible FAB button, but I don't especially like that idea)
2. Under what circumstances do we send accuracy / altitude information?

**Comment by SamWhited** [comment]
It just hit me that the answer is probably that the button should go to the users location, then change to a "pinned" mode (where it follows the user). To take it out of pinned mode and drag it, you just start dragging then the button changes back. The app would only send altitude/accuracy information when in pinned mode.

**Comment by dicer** [comment]
Ok, I didn't fully get what you were suggesting when I last commented. Now I do and I like the idea to fix the marker in the middle of the screen. When in pinned mode, the screen (and with it the marker) will always have the user in the middle, right? Button would then only show if you manually drag the map.
So that makes things very easy to understand for a user. It's more or less like all the mapping apps use the "return-to-location" button as well. 
Just that you also have a marker in the middle of the screen. This part is also implemented by openstreetmap.org when you share a location and include a marker. They also just place it in the middle of the screen.

**Comment by SamWhited** [comment]
I decided not to overthink gthe UI and just make this a menu item on <v21 devices and a fab button on v21 devices. It works quite nicely I think. Testing appreciated if anyone is building from source.
