### ISSUE TITLE
Feature request: Share location with navigation apps

### ISSUE THREAD

**Issue by kriztan** [SamWhited/OpenShareLocationPlugin#9]
It would be great if you can share a received location directly to a navigation app. Is this possible?
Thanks Kriztan

**Comment by SamWhited** [comment]
I'm not sure, I assumed they would show up in the list of apps in the share menu, but I'm not seeing anything there on mine either.

Will happily accept patches for this as long as the UI isn't too cumbersome.

**Comment by clonejo** [comment]
I guess this needs for a different intent than the share intent. This feature is a no-brainer.

**Comment by kriztan** [comment]
I'm not an Android programmer, but with a little google search I found this line 
`<category android:name="android.intent.category.APP_MAPS" />`
added to the manifest file. I don't know if it would work that way.

**Comment by SamWhited** [comment]
I looked around a bit this morning, but didn't see a consistent pattern being used across apps for this UI wise. The best thing I found was something like this:

![https://9to5google.files.wordpress.com/2014/11/gms-release-blog-nacho-map-toolbar.png](https://9to5google.files.wordpress.com/2014/11/gms-release-blog-nacho-map-toolbar.png)

However, it seems odd to me to have a "send" button in the action bar, and a similar "view" button elsewhere in the UI. Putting them together doesn't make a lot of sense contextually (share to another device vs. view on the current device).

I might accept pull requests, but right now I just don't see a clean way to do this in the UI.

**Comment by kriztan** [comment]
I've just installed OsmAnd and noticed that this app allows sharing a location to any other navigation apps. Perhaps this could help you: https://github.com/osmandapp/Osmand/blob/5c16ca9b5e9f55e0b8e7a598486b5d4cf53bd6ad/OsmAnd/src/net/osmand/plus/activities/actions/ShareLocation.java

**Comment by SamWhited** [comment]
It's not so much the technical side of this (which is really easy) but the UI side. I just don't see a way to do it cleanly that makes sense contextually with the rest of the UI.

**Comment by kriztan** [comment]
What about integrating it in the existing shring menu? Or doing it in that way OsmAnd does, with a menu to preselect how to share? To navigation app or as geo:URL?
![screenshot_2015-05-07-20-05-10](https://cloud.githubusercontent.com/assets/3350754/7522306/a661362e-f4f4-11e4-992c-9330e6cb7470.png)

**Comment by SamWhited** [comment]
> What about integrating it in the existing shring menu?

I don't think it makes sense to add them here contextually (mixing "sharing" vs. "opening with another app"). The existing menu is purely for sharing (the abstract action this represents is "send" while what we're doing with map apps is "open").

> Or doing it in that way OsmAnd does, with a menu to preselect how to share? To navigation app or as geo:URL?

Interesting; how do you get to that menu in OSMAnd (I should go download it and look).

**Comment by SamWhited** [comment]
Fixed. I'm not actually sure that I like the solution though, and right now it will only open in navigation apps that are compatible with Google Maps (as there's no standard intent for this). OSMAnd and Google Maps should work fine, but Waze does not.

If anyone knows other navigation apps that don't work, let me know; I'd love to know what other apps are doing here (or if they have a navigation intent at all).
